// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNetRogueLootAPI.Persistence;

namespace dotNetRogueLootAPI.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotNetRogueLootAPI.Domain.Models.Effect", b =>
                {
                    b.Property<string>("EffectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BonusDamage")
                        .HasColumnType("int");

                    b.Property<int>("BonusHealing")
                        .HasColumnType("int");

                    b.Property<int>("ExtraHits")
                        .HasColumnType("int");

                    b.Property<string>("WeaponNameFix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EffectName");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("dotNetRogueLootAPI.Domain.Models.WeaponRarity", b =>
                {
                    b.Property<string>("RarityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AmountOfEffects")
                        .HasColumnType("int");

                    b.Property<int>("AppearChance")
                        .HasColumnType("int");

                    b.Property<double>("StatModMul")
                        .HasColumnType("float");

                    b.HasKey("RarityName");

                    b.ToTable("WeaponRarities");
                });

            modelBuilder.Entity("dotNetRogueLootAPI.Domain.Models.WeaponType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("DodgeChance")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("WeaponTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
